name: 'test'

on:
  workflow_dispatch:

jobs:
  test-docker-sfx:
    name: docker-sfx-${{ matrix.image }}
    runs-on: windows-${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [2019, 2022]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          curl -LO https://mirror.msys2.org/distrib/msys2-x86_64-latest.sfx.exe
          docker build -t msys2-base -f ./Dockerfile.${{ matrix.image }} .

      - name: Test without Login Shell
        run: |
          docker run msys2-base C:\msys64\usr\bin\pacman.exe -Syy
          docker run msys2-base C:\msys64\usr\bin\pacman.exe --noconfirm -S vim

      - name: Test
        run: |
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman --version"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Qkv"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Qkk || true"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -Syy"
          docker run msys2-base C:\msys64\usr\bin\bash.exe -lc "pacman -S --noconfirm git"

